# Generated by Django 5.0.8 on 2024-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время привычки"
            ),
        ),
    ]
